version: '3.7'

services:

  nginx:
    build: ./nginx
    volumes:
      - media_volume:/usr/src/app/media/
      - static_volume:/usr/src/app/staticfiles/
    ports:
      - 9090:80
    depends_on:
      - web

  web:
    #build: ./app
    build: ./comicteca
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn comicteca.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media_volume:/usr/src/app/media/
      - static_volume:/usr/src/app/staticfiles/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=comicteca_user
      - POSTGRES_PASSWORD=comicteca_password
      - POSTGRES_DB=comicteca_dev
    # env_file:
    #  - ./.env.dev.db

volumes:
  postgres_data:
    name: django_postgres
    external: true
  static_volume:
    name: django_static
    external: true
  media_volume:
    name: django_media
    external: true

